<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BalancedMeds</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <Version>2.0.0</Version>
    <!-- The two lines below will set the output path for the binaries -->
    <OutputPath>bin\$(Configuration)\SPT_Runtime\user\mods\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="config\**\*" CopyToOutputDirectory="Always"/>
    <PackageReference Include="SPTushonka.Common" Version="4.1.2" />
    <PackageReference Include="SPTushonka.DI" Version="4.1.2" />
    <PackageReference Include="SPTushonka.Server.Core" Version="4.1.2" />
  </ItemGroup>

</Project>
