<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BalancedMeds</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <Version>2.1.0</Version>

    <!-- The two lines below will set the output path for the binaries  -->
    <OutputPath>bin\$(Configuration)\SPT_Runtime\user\mods\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <!-- ZIP -->
    <ZipFileName>BalancedMeds_v4_1_5.zip</ZipFileName>
    <ZipOutputPath>bin\$(Configuration)\$(ZipFileName)</ZipOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="config\**\*" CopyToOutputDirectory="Always"/>
    <PackageReference Include="SPTushonka.Common" Version="4.1.5" />
    <PackageReference Include="SPTushonka.DI" Version="4.1.5" />
    <PackageReference Include="SPTushonka.Server.Core" Version="4.1.5" />
  </ItemGroup>

  <Target Name="CreateReleaseZip"
        AfterTargets="Build"
        Condition="'$(Configuration)' == 'Release'">
    <PropertyGroup>
      <ZipSourcePath>$(MSBuildProjectDirectory)\bin\$(Configuration)\SPT_Runtime</ZipSourcePath>
      <ZipOutputPath>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(ZipFileName)</ZipOutputPath>
    </PropertyGroup>
    <Message Text="Creating release ZIP: $(ZipOutputPath)" Importance="high" />
    <Delete Files="$(ZipOutputPath)" />
    <Exec Command="powershell -NoProfile -ExecutionPolicy Bypass -Command &quot;Compress-Archive -Path '$(ZipSourcePath)' -DestinationPath '$(ZipOutputPath)' -Force&quot;" />
  </Target>

</Project>
